# Generated by Django 2.1.7 on 2019-02-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatDest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Categoria Destinatario',
                'verbose_name_plural': 'Categorie Destinatario',
            },
        ),
        migrations.CreateModel(
            name='Circolare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroProgressivo', models.SmallIntegerField()),
                ('AnnoScolastico', models.CharField(default='2018/2019', max_length=9)),
                ('Destinatario', models.TextField()),
                ('Oggetto', models.CharField(max_length=50)),
                ('DataPubblicazione', models.DateField(verbose_name='Data di Pubblicazione')),
                ('Allegato', models.TextField()),
                ('DataScadenza', models.DateField()),
                ('idCategoriaDest', models.ManyToManyField(to='Circolari.CatDest')),
            ],
            options={
                'verbose_name': 'Circolare',
                'verbose_name_plural': 'Circolari',
            },
        ),
    ]
