# Generated by Django 2.1.7 on 2019-02-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Circolari', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circolare',
            name='Allegato',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='circolare',
            name='DataScadenza',
            field=models.DateField(null=True),
        ),
    ]
