# Generated by Django 2.1.7 on 2019-02-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Circolari', '0002_auto_20190223_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circolare',
            old_name='idCategoriaDest',
            new_name='CategoriaDestinatari',
        ),
        migrations.AlterField(
            model_name='circolare',
            name='Allegato',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='circolare',
            name='AnnoScolastico',
            field=models.CharField(default='2018/2019', max_length=15),
        ),
        migrations.AlterField(
            model_name='circolare',
            name='DataScadenza',
            field=models.DateField(blank=True, null=True),
        ),
    ]
